### ISSUE TITLE
Absolute reference path in project

### ISSUE THREAD

**Issue by matthieubosquet** [langsamu/dotNetRDF.Dynamic#1]
An absolute reference in the csproj stops the project from building.

In file: https://github.com/langsamu/dotNetRDF.Dynamic/blob/d2fff12272c575ef01f25b347cd479561125792b/Libraries/dotNetRDF/dotNetRDF.csproj
Line:
`<DocumentationFile>C:\Users\samu\source\repos\dotNetRDF.Dynamic\Libraries\dotNetRDF\dotNetRDF.Dynamic.xml</DocumentationFile>`
Should be: 
`<DocumentationFile>.\dotNetRDF.Dynamic.xml</DocumentationFile>`

**Comment by langsamu** [comment]
Thx https://github.com/langsamu/dotNetRDF.Dynamic/commit/61f0505da23a1a34d3b9349195b6c3b909805b90
